#ifndef HEAP_ERRORS_H
#define HEAP_ERRORS_H

typedef enum {
  HEAP_SUCCESS = 0,

  HEAP_INIT_FAILED,
  HEAP_ALLOC_FAILED,
  HEAP_FREE_FAILED,
  HEAP_OUT_OF_MEMORY,

  HEAP_INVALID_POINTER,
  HEAP_DOUBLE_FREE,
  HEAP_INVALID_SIZE,
  HEAP_NOT_INITIALIZED,

  HEAP_OVERFLOW,
  HEAP_UNDERFLOW,
  HEAP_ALIGNMENT_ERROR,
  HEAP_BOUNDARY_ERROR,

  HEAP_CORRUPTION_DETECTED,
  HEAP_SPRAY_ATTACK,
  HEAP_UNKNOWN_ERROR
} HeapErrorCode;

const char* heap_error_what(HeapErrorCode code);

#endif /* HEAP_ERRORS_H */
